AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  events


# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  EventHandlerFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: event_handler/
      Handler: app.lambda_handler
      Runtime: ruby2.7
      Policies:
        - VPCAccessPolicy: {}
        - SSMParameterReadPolicy:
            ParameterName: PUSHER_APP_ID
        - SSMParameterReadPolicy:
            ParameterName: PUSHER_KEY
        - SSMParameterReadPolicy:
            ParameterName: PUSHER_SECRET
        - SSMParameterReadPolicy:
            ParameterName: PUSHER_CHANNEL
      Events:
        Ingestion:
          Type: SNS
          Properties:
            Topic: arn:aws:sns:eu-west-1:527475777899:relay

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  EventHandlerFunction:
    Description: "Event Handler Lambda Function ARN"
    Value: !GetAtt EventHandlerFunction.Arn
  EventHandlerFunctionIamRole:
    Description: "Implicit IAM Role created for Event Handler function"
    Value: !GetAtt EventHandlerFunctionRole.Arn
