version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "home"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1w4bztqyd1r4f"
s3_prefix = "home"
region = "eu-west-1"
capabilities = "CAPABILITY_IAM"

